name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.15.0
  - astor=0.8.1
  - blas=1.0
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2021.5.30
  - coverage=5.5
  - cycler=0.11.0
  - cython=0.29.24
  - dataclasses=0.8
  - freetype=2.11.0
  - gast=0.5.3
  - grpcio=1.36.1
  - importlib-metadata=4.8.1
  - intel-openmp=2022.0.0
  - jpeg=9e
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - pillow=8.3.1
  - pip=21.2.2
  - protobuf=3.17.2
  - pyparsing=3.0.4
  - python=3.6.13
  - python-dateutil=2.8.2
  - python_abi=3.6
  - readline=8.1.2
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.38.3
  - tensorboard=1.10.0
  - tensorflow=1.10.0
  - tensorflow-base=1.10.0
  - termcolor=1.1.0
  - tk=8.6.12
  - tornado=6.1
  - typing_extensions=4.1.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.6.0
  - zlib=1.2.12
  - zstd=1.5.2
